### ISSUE TITLE
Editing plex objects

### ISSUE THREAD

**Issue by Inrixia** [TypeCtrl/plex#14]
Hia, Library works great for reading data from plex but whenever I want to try edit/update properties I cant seem to get it to work.
Ideally I want to be able to set a Show/Movies Banner to a given URL that contains a image. 

But even trying something as simple as updating the title does not seem to work. Is there some decent documentation on how to use .edit?

![image](https://user-images.githubusercontent.com/6373693/110950057-3f9e1080-83a8-11eb-87a5-b37d3c11896b.png)

**Comment by scttcper** [comment]
@Inrixia should be working with the right parameters now when a new versions publishes. Title would be 
```show.edit({ 'title.value': 'new title' })```

I'm not sure how you would guess that its "title.value" without opening plex web and doing an edit there and looking at what it sends.

**Comment by scttcper** [comment]
hmmm... going to have to figure out why CI is broken later

**Comment by Inrixia** [comment]
This still doesnt appear to be working sorry
![image](https://user-images.githubusercontent.com/6373693/111058620-a3355480-84f4-11eb-9b6a-4ccf056f7fcd.png)

**Comment by Inrixia** [comment]
I've checked and it appears that title.value should be correct. I'm not sure if its user error and I need to be passing more info or if its a problem with how the request is being sent...
![image](https://user-images.githubusercontent.com/6373693/111058654-cd871200-84f4-11eb-9d5c-1e1c3feba2e6.png)

**Comment by scttcper** [comment]
make sure you're on v1.5.1

if you could catch the error and log the url being used - make sure to omit the plex token
```ts
  try {
    await shows[0].edit({ 'title.value': 'xxx' });
  } catch (err) {
    console.log(err.request.options.url);
  }
```

**Comment by scttcper** [comment]
hmm might need to call reload() on the object being edited

**Comment by scttcper** [comment]
Alright i have it calling reload for you if librarySectionID is missing, which is hopefully what does it.

**Comment by Inrixia** [comment]
Will test when I get the chance, thanks :)

**Comment by Inrixia** [comment]
Getting this now 
![image](https://user-images.githubusercontent.com/6373693/111101418-b4db3280-85ae-11eb-84f0-a7cc9c566f7c.png)

**Comment by scttcper** [comment]
@Inrixia looks like its looking for the type, if you pass a type to edit it would fix it until i figure out why your object is missing it. In the url you posted earlier it was type: 2. 

```ts
await show.edit({ 'title.value': 'xxx', type: 2 });
```

related line
https://github.com/scttcper/plex/blob/master/src/base/partialPlexObject.ts#L265

**Comment by Inrixia** [comment]
Ran into this error
![image](https://user-images.githubusercontent.com/6373693/111108716-4aca8980-85be-11eb-8f33-fd7dc38505a6.png)

Ratingkey is undefined so when the id is set its undefined resulting in the error thrown. Commenting out ratingKey being set makes it work though! But it seems that it has set every show's title instead of just the title of the selected show, so I presume the lack of a ratingKey is the reason for that.

**Comment by scttcper** [comment]
okay added test coverage for editing a show title and hopefully finally have a fix in this latest version

**Comment by Inrixia** [comment]
Looks like its working. Thanks!
